// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aixitdzrrrudypcnslfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpeGl0ZHpycnJ1ZHlwY25zbGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTgwMDgsImV4cCI6MjA3MzE5NDAwOH0.-2gl-Sh2xteBEn80BRWic0TS4kuRuC8nk1jDLwbQG00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});